import type { Metadata } from "next";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
const raleway = localFont({
  src: "../fonts/Raleway.woff2",
  variable: "--font-raleway",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "MUSLISH Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        `${raleway.variable}`,
      )}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <Header />
          <main className="flex-1">
            {children}
            <Toaster position="bottom-right" toastOptions={{style: {background: "#000000", color: "#ffffff"}}}/>
            </main>
          <Footer />
        
        </ClerkProvider>
      </body>
    </html>
  );
}
